import argparse
import asyncio
import json
import os
import tempfile

import edge_tts
import numpy as np
import soundfile as sf

from app.schemas import CompetencyFramework, DialogueScript, EvaluationChecklist, JobDescription
from scripts.interview_profiles import PROFILES, InterviewProfile

# Constants for default configurations
DEFAULT_OUTPUT_DIR = "data/synthetic"


# Backwards-compatible accessors for the original single-profile API
def get_sample_job_description() -> JobDescription:
    return PROFILES["python_pleno"].job


def get_sample_competency_framework() -> CompetencyFramework:
    return PROFILES["python_pleno"].competencies


def get_sample_evaluation_checklist() -> EvaluationChecklist:
    return PROFILES["python_pleno"].checklist


def get_sample_dialogue_script() -> DialogueScript:
    return PROFILES["python_pleno"].dialogue


async def synthesize_turn(text: str, voice: str, filepath: str) -> None:
    """Synthesizes text to a single MP3 file using edge-tts."""
    communicate = edge_tts.Communicate(text, voice)
    await communicate.save(filepath)


async def generate_interview_audio(
    script: DialogueScript,
    interviewer_voice: str,
    candidate_voice: str,
    output_wav_path: str
) -> None:
    """
    Synthesizes each dialogue turn, reads the temporary files using soundfile,
    concatenates them with small silences, and saves the final WAV audio.
    """
    temp_files = []

    try:
        # Create temp files for each turn
        for i, turn in enumerate(script.turns):
            voice = interviewer_voice if turn.speaker == "Entrevistador" else candidate_voice
            temp_fd, temp_path = tempfile.mkstemp(suffix=".mp3")
            os.close(temp_fd) # Close file descriptor so edge-tts can write to it
            temp_files.append(temp_path)

            print(f"Synthesizing turn {i+1}/{len(script.turns)} ({turn.speaker})...")
            await synthesize_turn(turn.text, voice, temp_path)

        print("Concatenating audio turns...")
        combined_audio = []
        samplerate = None

        # 0.5 seconds of silence at 24000Hz (default samplerate for edge-tts)
        silence_duration_seconds = 0.5

        for i, path in enumerate(temp_files):
            data, sr = sf.read(path)
            if samplerate is None:
                samplerate = sr
            elif sr != samplerate:
                # In practice they should be the same as they are generated by the same service
                pass

            # Append audio data
            combined_audio.append(data)

            # If not the last turn, append silence
            if i < len(temp_files) - 1:
                silence_length = int(silence_duration_seconds * samplerate)
                # Since edge-tts outputs mono audio, data is 1D array.
                silence = np.zeros(silence_length)
                combined_audio.append(silence)

        # Concatenate all parts
        final_audio = np.concatenate(combined_audio)

        # Ensure output directory exists
        os.makedirs(os.path.dirname(output_wav_path), exist_ok=True)

        # Save to WAV format
        sf.write(output_wav_path, final_audio, samplerate)
        print(f"Final audio saved to: {output_wav_path}")

    finally:
        # Clean up temporary MP3 files
        for path in temp_files:
            if os.path.exists(path):
                try:
                    os.remove(path)
                except OSError as e:
                    print(f"Failed to delete temp file {path}: {e}")


def generate_profile_files(profile: InterviewProfile, output_dir: str) -> str:
    """Writes the job/competency/checklist/dialogue JSON files for a profile."""
    prefix = profile.prefix
    paths = {
        "job": os.path.join(output_dir, f"job_{prefix}.json"),
        "competency": os.path.join(output_dir, f"competency_{prefix}.json"),
        "checklist": os.path.join(output_dir, f"checklist_{prefix}.json"),
        "dialogue": os.path.join(output_dir, f"interview_{prefix}.json"),
    }

    with open(paths["job"], "w", encoding="utf-8") as f:
        json.dump(profile.job.model_dump(), f, indent=2, ensure_ascii=False)
    with open(paths["competency"], "w", encoding="utf-8") as f:
        json.dump(profile.competencies.model_dump(), f, indent=2, ensure_ascii=False)
    with open(paths["checklist"], "w", encoding="utf-8") as f:
        json.dump(profile.checklist.model_dump(), f, indent=2, ensure_ascii=False)
    with open(paths["dialogue"], "w", encoding="utf-8") as f:
        json.dump(profile.dialogue.model_dump(), f, indent=2, ensure_ascii=False)

    for path in paths.values():
        print(f"Saved: {path}")
    return os.path.join(output_dir, f"interview_{prefix}.wav")


def main():
    parser = argparse.ArgumentParser(description="Synthetic Data Generator for Scorecard Pipeline")
    parser.add_argument("--output-dir", default=DEFAULT_OUTPUT_DIR, help="Directory to save generated files")
    parser.add_argument(
        "--profile",
        default="all",
        choices=["all"] + sorted(PROFILES.keys()),
        help="Interview profile to generate (default: all)"
    )
    parser.add_argument(
        "--skip-audio",
        action="store_true",
        help="Generate only the JSON files, skipping TTS audio synthesis"
    )
    parser.add_argument("--interviewer-voice", default=None, help="Override interviewer voice")
    parser.add_argument("--candidate-voice", default=None, help="Override candidate voice")

    args = parser.parse_args()

    os.makedirs(args.output_dir, exist_ok=True)

    selected = list(PROFILES.values()) if args.profile == "all" else [PROFILES[args.profile]]

    for profile in selected:
        print(f"\n=== Generating profile '{profile.prefix}' "
              f"(expected outcome: {profile.expected_outcome}) ===")
        audio_path = generate_profile_files(profile, args.output_dir)

        if args.skip_audio:
            print("Skipping audio synthesis (--skip-audio).")
            continue

        print("Generating interview audio (this may take a few minutes)...")
        asyncio.run(
            generate_interview_audio(
                profile.dialogue,
                args.interviewer_voice or profile.interviewer_voice,
                args.candidate_voice or profile.candidate_voice,
                audio_path
            )
        )

    print("\nGeneration completed successfully!")


if __name__ == "__main__":
    main()
